package org.eclipse.epsilon.eol.ast2eol.test;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({ AbortStatementCreatorTest.class,
		AndOperatorExpressionCreatorTest.class,
		AnnotationBlockCreatorTest.class, AnyTypeCreatorTest.class,
		AssignmentStatementCreatorTest.class, BagExpressionCreatorTest.class,
		BagTypeCreatorTest.class, BlockCreatorTest.class,
		BooleanExpressionCreatorTest.class, BooleanTypeCreatorTest.class,
		BreakAllStatementCreatorTest.class, BreakStatementCreatorTest.class,
		CollectionTypeCreatorTest.class, ContinueStatementCreatorTest.class,
		DeleteStatementCreatorTest.class,
		DivideOperatorExpressionCreatorTest.class,
		EnumerationLiteralExpressionCreatorTest.class,
		EOLModuleCreatorTest.class, EqualsOperatorExpressionCreatorTest.class,
		ExecutableAnnotationCreatorTest.class, ExpressionRangeCreatorTest.class,
		ExpressionOrStatementBlockCreatorTest.class,
		ExpressionStatementCreatorTest.class, ExpressionListCreatorTest.class,
		FOLMethodCallExpressionCreatorTest.class,
		FormalParameterExpressionCreatorTest.class,
		ForStatementCreatorTest.class,
		GreaterThanOperatorExpressionCreatorTest.class,
		GreaterThanOrEqualToOperatorExpressionCreatorTest.class,
		IfStatementCreatorTest.class,
		ImpliesOperatorExpressionCreatorTest.class, ImportCreatorTest.class,
		IntegerExpressionCreatorTest.class, IntegerTypeCreatorTest.class,
		KeyValueExpressionCreatorTest.class, LessThanOperatorExpressionCreatorTest.class,
		LessThanOrEqualToOperatorExpressionCreatorTest.class,
		MapExpressionCreatorTest.class, MapTypeCreatorTest.class,
		MethodCallExpressionCreatorTest.class,
		MinusOperatorExpressionCreatorTest.class,
		ModelDeclarationParameterCreatorTest.class,
		ModelDeclarationStatementCreatorTest.class,
		//ModelElementTypeCreatorTest.class, ModelExpressionCreatorTest.class,
		ModelTypeCreatorTest.class,
		MultiplyOperatorExpressionCreatorTest.class,
		//NativeExpressionCreatorTest.class, NativeTypeCreatorTest.class,
		NegativeOperatorExpressionCreatorTest.class,
		NewExpressionCreatorTest.class,
		NotEqualsOperatorExpressionCreatorTest.class,
		NotOperatorExpressionCreatorTest.class,
		//OperationArgTypeCreatorTest.class,
		OperationDefinitionCreatorTest.class,
		OrderedSetExpressionCreatorTest.class, OrderedSetTypeCreatorTest.class,
		OrOperatorExpressionCreatorTest.class,
		PlusOperatorExpressionCreatorTest.class,
		PropertyCallExpressionCreatorTest.class, PseudoTypeCreatorTest.class,
		RealExpressionCreatorTest.class, RealTypeCreatorTest.class,
		ReturnStatementCreatorTest.class, SelfContentTypeCreatorTest.class,
		SelfInnerMostTypeCreatorTest.class, SelfTypeCreatorTest.class,
		SequenceExpressionCreatorTest.class, SequenceTypeCreatorTest.class,
		SetExpressionCreatorTest.class, SetTypeCreatorTest.class,
		SimpleAnnotationCreatorTest.class,
		SpecialAssignmentStatementCreatorTest.class,
		StringExpressionCreatorTest.class, StringTypeCreatorTest.class,
		SwitchCaseDefaultCreatorTest.class,
		SwitchCaseExpressionCreatorTest.class,
		SwitchStatementCreatorTest.class, ThrowStatementCreatorTest.class,
		TransactionStatementCreatorTest.class,
		VariableDeclarationExpressionCreatorTest.class,
		WhileStatementCreatorTest.class, XorOperatorExpressionCreatorTest.class })
public class AllTests {

}
