<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="library" nsURI="http://library/1.0" nsPrefix="library">
  <eClassifiers xsi:type="ecore:EClass" name="t_library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" upperBound="-1" eType="//t_book" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="t_book">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" eType="//t_library" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" upperBound="-1" eType="//t_author" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="published" eType="//t_published" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="t_author">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" eType="//t_book" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="t_published">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" eType="//t_book" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
