<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="etl" nsURI="http://www.eclipse.org/epsilon/etl" nsPrefix="etl">
  <eAnnotations source="emf.gen">
    <details key="classPackageSuffix" value="metamodel.impl"/>
    <details key="utilityPackageSuffix" value="metamodel.util"/>
    <details key="metaDataPackageSuffix" value="metamodel"/>
    <details key="interfacePackageSuffix" value="metamodel"/>
    <details key="basePackage" value="org.eclipse.epsilon"/>
  </eAnnotations>
  <eAnnotations source="emf.gen.usedGenPackage">
    <details key="name" value="eol"/>
    <details key="genModel" value="platform:/resource/org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.genmodel"/>
  </eAnnotations>
  <eAnnotations source="emf.gen.annotation">
    <details key="source" value="emf.gen"/>
    <details key="key" value="extends"/>
    <details key="value" value="eol"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ETLElement" eSuperTypes="../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//EOLElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedBlock" eSuperTypes="#//ETLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//NameExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETLModule" eSuperTypes="../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//EOLLibraryModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationRules" upperBound="-1"
        eType="#//TransformationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preBlocks" upperBound="-1"
        eType="#//NamedBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postBlocks" upperBound="-1"
        eType="#//NamedBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationRule" eSuperTypes="#//ETLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//NameExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//FormalParameterExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//FormalParameterExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationBlock" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//AnnotationBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//NameExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedParentRules" upperBound="-1"
        eType="#//TransformationRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedRuleDependencies"
        upperBound="-1" eType="#//RuleDependency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//ExpressionOrStatementBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="greedy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleDependency" eSuperTypes="#//ETLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependingRule" eType="#//TransformationRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" eType="ecore:EClass ../../org.eclipse.epsilon.haetae.eol.metamodel/model/EOL.ecore#//EOLElement"/>
  </eClassifiers>
</ecore:EPackage>
